import { StyleSheet } from 'react-native'

import { colors, fonts, radii } from '../../../theme/tokens'

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.canvas,
    flex: 1,
  },
  keyboardArea: {
    flex: 1,
  },
  page: {
    flex: 1,
  },
  shell: {
    backgroundColor: colors.canvas,
    flex: 1,
    overflow: 'hidden',
    width: '100%',
  },
  desktopShell: {
    flexDirection: 'row',
  },
  mobileShell: {
    minHeight: '100%',
  },
  visualPane: {
    backgroundColor: '#0E1524',
    overflow: 'hidden',
    position: 'relative',
  },
  visualDesktop: {
    flex: 1.04,
    paddingBottom: 30,
    paddingHorizontal: 56,
    paddingTop: 30,
  },
  visualMobile: {
    minHeight: 320,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  orangePanel: {
    backgroundColor: colors.brand,
    borderBottomLeftRadius: 70,
    borderTopLeftRadius: 70,
    bottom: -28,
    height: '74%',
    position: 'absolute',
    right: -12,
    top: '18%',
    width: '50%',
  },
  orangeHalo: {
    backgroundColor: '#FFB783',
    borderRadius: 1000,
    bottom: -98,
    height: 390,
    opacity: 0.2,
    position: 'absolute',
    right: 68,
    width: 390,
  },
  orangeGlow: {
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    height: 170,
    opacity: 0.1,
    position: 'absolute',
    right: 96,
    top: 170,
    width: 170,
  },
  brandLogo: {
    height: 62,
    width: 161,
    zIndex: 3,
  },
  visualCopy: {
    marginTop: 78,
    maxWidth: 330,
    zIndex: 2,
  },
  visualCopyMobile: {
    marginTop: 34,
    maxWidth: 250,
  },
  visualKicker: {
    color: '#D6F7DF',
    fontFamily: fonts.regular,
    fontSize: 11,
    letterSpacing: 0,
    marginBottom: 22,
  },
  visualPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.14)',
    borderRadius: radii.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    marginBottom: 24,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  visualPillDot: {
    backgroundColor: '#6EE7A8',
    borderRadius: 5,
    height: 9,
    width: 9,
  },
  visualPillText: {
    color: '#E7FFF1',
    fontFamily: fonts.regular,
    fontSize: 10,
    letterSpacing: 0.6,
  },
  visualTitle: {
    color: colors.white,
    fontFamily: fonts.light,
    fontSize: 42,
    letterSpacing: 0,
    lineHeight: 52,
  },
  visualTitleMobile: {
    fontSize: 26,
    lineHeight: 33,
  },
  visualSubtitle: {
    color: 'rgba(255, 255, 255, 0.64)',
    fontFamily: fonts.light,
    fontSize: 14,
    lineHeight: 24,
    marginTop: 18,
    maxWidth: 300,
  },
  featureRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 26,
    maxWidth: 315,
  },
  featureChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: radii.pill,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  featureChipText: {
    color: 'rgba(255, 255, 255, 0.76)',
    fontFamily: fonts.light,
    fontSize: 11,
  },
  flowRail: {
    marginTop: 30,
    width: '100%',
  },
  flowSteps: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  flowStepWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  flowIconCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 18,
    borderWidth: 1,
    height: 82,
    justifyContent: 'center',
    paddingHorizontal: 8,
    width: 82,
  },
  flowIcon: {
    height: 48,
    width: 48,
  },
  flowStepText: {
    color: 'rgba(255, 255, 255, 0.82)',
    fontFamily: fonts.regular,
    fontSize: 10,
    marginTop: 3,
  },
  flowArrow: {
    color: 'rgba(255, 255, 255, 0.42)',
    fontFamily: fonts.light,
    fontSize: 14,
  },
  illustration: {
    zIndex: 1,
  },
  illustrationDesktop: {
    bottom: 2,
    position: 'absolute',
    right: -18,
    width: '54%',
  },
  illustrationMobile: {
    bottom: -34,
    position: 'absolute',
    right: -52,
    width: 260,
  },
  formPane: {
    backgroundColor: colors.canvas,
    justifyContent: 'center',
    position: 'relative',
  },
  formDesktop: {
    flex: 0.96,
    minHeight: 720,
    paddingHorizontal: 72,
    paddingVertical: 36,
  },
  formMobile: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingBottom: 28,
    paddingHorizontal: 22,
    paddingTop: 68,
  },
  formContent: {
    alignSelf: 'center',
    maxWidth: 412,
    width: '100%',
  },
  forgotContent: {
    maxWidth: 430,
  },
  mobileFormContent: {
    maxWidth: 350,
  },
  mobileLogo: {
    alignSelf: 'center',
    height: 62,
    marginBottom: 26,
    width: 161,
  },
  mobileKicker: {
    fontSize: 10,
    marginBottom: 11,
    textAlign: 'center',
  },
  mobileTitle: {
    fontFamily: fonts.regular,
    fontSize: 23,
    lineHeight: 31,
    textAlign: 'center',
  },
  mobileSubtitle: {
    fontSize: 13,
    lineHeight: 22,
    marginBottom: 30,
    marginTop: 12,
    textAlign: 'center',
  },
  formKicker: {
    color: colors.brandPressed,
    fontFamily: fonts.regular,
    fontSize: 11,
    letterSpacing: 0,
    marginBottom: 13,
  },
  formTitle: {
    color: colors.ink,
    fontFamily: fonts.regular,
    fontSize: 37,
    letterSpacing: 0,
    lineHeight: 47,
  },
  formSubtitle: {
    color: colors.muted,
    fontFamily: fonts.light,
    fontSize: 14,
    lineHeight: 24,
    marginBottom: 32,
    marginTop: 10,
  },
  fields: {
    gap: 17,
    marginBottom: 18,
  },
  textFieldGroup: {
    gap: 7,
  },
  textFieldLabel: {
    color: colors.text,
    fontFamily: fonts.regular,
    fontSize: 12,
  },
  textFieldRow: {
    alignItems: 'center',
    backgroundColor: colors.input,
    borderColor: colors.border,
    borderRadius: radii.xSmall,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 56,
    paddingHorizontal: 13,
  },
  textFieldRowError: {
    backgroundColor: colors.dangerSoft,
    borderColor: '#E4AAAA',
  },
  textFieldIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.brandSoft,
    borderRadius: 7,
    height: 30,
    justifyContent: 'center',
    marginRight: 11,
    width: 30,
  },
  textFieldIcon: {
    color: colors.brandPressed,
    fontFamily: fonts.regular,
    fontSize: 12,
    textAlign: 'center',
  },
  textFieldInput: {
    color: colors.ink,
    flex: 1,
    fontFamily: fonts.light,
    fontSize: 14,
    paddingVertical: 14,
  },
  textFieldShowButton: {
    color: colors.brandPressed,
    fontFamily: fonts.regular,
    fontSize: 11,
    marginLeft: 10,
  },
  textFieldError: {
    color: colors.danger,
    fontFamily: fonts.light,
    fontSize: 11,
  },
  formOptions: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rememberButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
  },
  checkbox: {
    alignItems: 'center',
    borderColor: colors.borderStrong,
    borderRadius: 6,
    borderWidth: 1,
    height: 19,
    justifyContent: 'center',
    width: 19,
  },
  checkboxChecked: {
    backgroundColor: colors.brand,
    borderColor: colors.brand,
  },
  checkboxMark: {
    backgroundColor: colors.white,
    borderRadius: 3,
    height: 7,
    width: 7,
  },
  optionText: {
    color: colors.text,
    fontFamily: fonts.light,
    fontSize: 12,
  },
  forgotText: {
    color: colors.brandPressed,
    fontFamily: fonts.regular,
    fontSize: 12,
  },
  forgotTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 34,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: colors.brandWash,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  backIcon: {
    color: colors.brandPressed,
    fontFamily: fonts.regular,
    fontSize: 12,
  },
  backText: {
    color: colors.brandPressed,
    fontFamily: fonts.regular,
    fontSize: 11,
  },
  resetBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.brandSoft,
    borderRadius: radii.pill,
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  resetBadgeText: {
    color: colors.brandPressed,
    fontFamily: fonts.regular,
    fontSize: 10,
    letterSpacing: 0.5,
  },
  forgotTitle: {
    fontSize: 35,
    lineHeight: 44,
  },
  forgotSubtitle: {
    marginBottom: 28,
  },
  submitButton: {
    alignItems: 'center',
    backgroundColor: colors.brand,
    borderRadius: radii.medium,
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 28,
    minHeight: 58,
    paddingHorizontal: 20,
    shadowColor: colors.brandPressed,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
  },
  submitButtonPressed: {
    backgroundColor: colors.brandPressed,
    transform: [{ scale: 0.997 }],
  },
  resetButton: {
    marginTop: 10,
  },
  submitText: {
    color: colors.white,
    fontFamily: fonts.medium,
    fontSize: 14,
  },
  submitArrow: {
    color: colors.white,
    fontFamily: fonts.regular,
    fontSize: 16,
    marginLeft: 10,
  },
  notice: {
    backgroundColor: colors.successSoft,
    borderColor: '#C5E5D3',
    borderRadius: radii.medium,
    borderWidth: 1,
    marginTop: 15,
    padding: 12,
  },
  noticeText: {
    color: colors.success,
    fontFamily: fonts.light,
    fontSize: 11,
    lineHeight: 18,
    textAlign: 'center',
  },
  helpText: {
    color: colors.muted,
    fontFamily: fonts.light,
    fontSize: 11,
    marginTop: 28,
    textAlign: 'center',
  },
  helpLink: {
    color: colors.text,
    fontFamily: fonts.regular,
  },
})
